# Generated by Django 6.0.2 on 2026-02-21 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("timesheet", "0003_finalize_employee_code_constraint"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={"ordering": ["-start_date", "name"]},
        ),
        migrations.AlterModelOptions(
            name="projectallocation",
            options={"ordering": ["-start_date"]},
        ),
    ]
