# Generated by Django 4.2.28 on 2026-02-21 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0002_alter_employee_id_alter_project_id_and_more'),
        ('timesheet', '0003_finalize_employee_code_constraint'),
    ]

    operations = [
    ]
