# Generated by Django 4.2.28 on 2026-02-21 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0004_alter_project_options_and_more'),
        ('timesheet', '0004_merge_20260221_1245'),
    ]

    operations = [
    ]
