# Generated by Django 4.2.28 on 2026-03-07 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0005_merge_20260221_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('REQUIREMENT_ANALYSIS', 'Requirement Analysis'), ('DEVELOPMENT', 'Development'), ('TESTING', 'Testing'), ('DEPLOYMENT', 'Deployment'), ('COMPLETED', 'Completed')], default='PLANNING', max_length=20),
        ),
    ]
