# Generated by Django 4.2.28 on 2026-03-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0006_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectallocation',
            name='allocation_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
