# Generated by Django 4.2.28 on 2026-03-07 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0008_employee_is_active_employee_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesheetentry',
            name='task_reference',
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('REQUIREMENT_ANALYSIS', 'Requirement Analysis'), ('DEVELOPMENT', 'Development'), ('TESTING', 'Testing'), ('DEPLOYMENT', 'Deployment'), ('COMPLETED', 'Completed')], default='REQUIREMENT_ANALYSIS', max_length=25),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='timesheet.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='timesheet.project')),
            ],
        ),
        migrations.AddField(
            model_name='timesheetentry',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='timesheet.task'),
        ),
    ]
