# Generated by Django 4.2.28 on 2026-04-02 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0013_task_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('logo', models.ImageField(upload_to='logos/')),
                ('content_image', models.ImageField(upload_to='content/')),
                ('instagram_image', models.ImageField(blank=True, null=True, upload_to='posters/insta/')),
                ('whatsapp_image', models.ImageField(blank=True, null=True, upload_to='posters/whatsapp/')),
                ('facebook_image', models.ImageField(blank=True, null=True, upload_to='posters/facebook/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
