# Generated by Django 4.2.28 on 2026-04-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0014_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='content_video',
            field=models.FileField(blank=True, null=True, upload_to='videos/content/'),
        ),
        migrations.AddField(
            model_name='poster',
            name='video_facebook',
            field=models.FileField(blank=True, null=True, upload_to='videos/facebook/'),
        ),
        migrations.AddField(
            model_name='poster',
            name='video_instagram',
            field=models.FileField(blank=True, null=True, upload_to='videos/insta/'),
        ),
        migrations.AddField(
            model_name='poster',
            name='video_whatsapp',
            field=models.FileField(blank=True, null=True, upload_to='videos/whatsapp/'),
        ),
    ]
