# Generated by Django 4.2.28 on 2026-04-03 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timesheet', '0015_poster_content_video_poster_video_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='video_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/'),
        ),
    ]
